function import_data(FILETOREAD1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-Sep-2009 10:19:17



% Import the file
newData1 = load('-mat', FILETOREAD1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1)
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}))
end